### ISSUE TITLE
Hello sir 

### ISSUE THREAD

**Issue by yogesh1122** [codersgyan/realtime-pizza-app-node-express-mongo#1]
secret option required for sessions
at session (H:\realtime-pizza-app-node-express-mongo-master\realtime-pizza-app-node-express-mongo-master\node_modules\express-session\index.js:200:12)
    at Layer.handle [as handle_request] (H:\realtime-pizza-app-node-express-mongo-master\realtime-pizza-app-node-express-mongo-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (H:\realtime-pizza-app-node-express-mongo-master\realtime-pizza-app-node-express-mongo-master\node_modules\express\lib\router\index.js:317:13)
    
Shows an error please fix this because when i install not working this code

**Comment by yogesh1122** [comment]
not solve

**Comment by Nike-rgb** [comment]
Hey, I know this is late but, have you configured your .env file? This is probably why it's showing that error. You have to make your own .env file on your machine, and set up the environment variables(refer to .envexample inside the repo for reference).
